insert into public.aircraft (
  tail,
  icao24,
  home_state_code,
  operator,
  model,
  nickname,
  base,
  role,
  role_confidence,
  role_description,
  role_note
)
values
  ('N305DK', 'A3323A', 'WA', 'WSP', 'Cessna 206H Stationair (FLIR)', 'Bird 4', 'KOLM Olympia', 'fixed_wing', 'confirmed', 'Speed enforcement', 'Bird 4 — WSP fixed-wing FLIR'),
  ('N305RC', 'A3335F', 'WA', 'WSP', 'Cessna 182T Skylane', null, 'KOLM Olympia', 'fixed_wing', 'confirmed', 'Speed enforcement', 'WSP fixed-wing speed enforcement'),
  ('N2446X', 'A2421B', 'WA', 'WSP', 'Cessna 206H Stationair (FLIR)', 'Bird 3', 'KOLM Olympia', 'fixed_wing', 'confirmed', 'Speed enforcement', 'Bird 3 — WSP fixed-wing FLIR'),
  ('N102LP', 'A00D2A', 'WA', 'WSP', 'Cessna 182T Skylane', null, 'KOLM Olympia', 'fixed_wing', 'confirmed', 'Speed enforcement', 'WSP fixed-wing speed enforcement'),
  ('N3532K', 'A3F29A', 'WA', 'WSP', 'Cessna 182T Skylane', null, 'KOLM Olympia', 'fixed_wing', 'confirmed', 'Speed enforcement', 'WSP fixed-wing speed enforcement'),
  ('N207HB', 'A1ACB5', 'WA', 'State of WA', 'Beechcraft B200 Super King Air', null, 'KOLM Olympia (WSP-operated)', 'transport', 'tentative', 'Transport / multi-mission (all-weather)', 'WSP-flown all-weather King Air; owned by State of WA'),
  ('N422CT', 'A50351', 'WA', 'KCSO', 'Bell 407GXi', 'Guardian One', 'KRNT Renton', 'patrol', 'confirmed', 'Patrol / pursuit / SAR', 'Guardian One — multi-role'),
  ('N407KS', 'A4C794', 'WA', 'KCSO', 'Bell 407', 'Guardian One (legacy)', 'KRNT Renton', 'patrol', 'tentative', 'Patrol / pursuit (backup)', 'Guardian One legacy airframe'),
  ('N411KS', 'A4D8C9', 'WA', 'KCSO', 'Bell 206B JetRanger', null, 'KRNT Renton', 'patrol', 'tentative', 'Patrol / training', 'Former KCSO Bell 206B / JetRanger'),
  ('N790RJ', 'AAB985', 'WA', 'KCSO', 'Bell UH-1H Iroquois', 'Guardian Two', 'KRNT Renton', 'sar', 'tentative', 'SAR / SWAT insertion', 'Guardian Two — likely SAR/SWAT'),
  ('N71KP', 'A97AA3', 'WA', 'KCSO', 'Bell UH-1H Iroquois', null, 'KRNT Renton', 'sar', 'tentative', 'SAR / SWAT (reserve)', 'KCSO reserve Huey'),
  ('N67817', 'A8FC0B', 'WA', 'KCSO', 'Bell 206B / TH-67A Creek', null, 'KRNT Renton', 'patrol', 'tentative', 'Patrol / training', 'KCSO Bell 206/TH-67'),
  ('N67880', 'A8FCF9', 'WA', 'KCSO', 'Bell 206B / TH-67A Creek', null, 'KRNT Renton', 'patrol', 'tentative', 'Patrol / training', 'KCSO Bell 206/TH-67'),
  ('N78906', 'AAB46C', 'WA', 'KCSO', 'Bell 206B / TH-67A Creek', null, 'KRNT Renton', 'patrol', 'tentative', 'Patrol / training', 'KCSO Bell 206/TH-67'),
  ('N9446P', 'AD1F3C', 'WA', 'Pierce SO', 'Cessna T206H Stationair (FLIR)', 'Pierce One', 'KPLU Thun Field, Puyallup', 'fixed_wing', 'confirmed', 'Patrol / SAR / port security', 'Pierce One — Cessna T206H FLIR (2012)'),
  ('N815SC', 'AB1D82', 'WA', 'Snohomish SO', 'Bell UH-1H Iroquois Plus', 'SnoHawk 10', 'Taylor''s Landing', 'sar', 'tentative', 'Mountain SAR / hoist / SWAT', 'SnoHawk 10 — likely SAR'),
  ('N509DV', 'A65BBE', 'WA', 'Spokane SO', 'Bell 505 Jet Ranger X', 'Air 1', 'KSFF Felts Field, Spokane', 'patrol', 'tentative', 'Patrol / SAR / fugitive apprehension', 'Spokane SO Bell 505 — likely Air 1 since 2024'),
  ('N1977G', 'A18580', 'WA', 'CBP', 'Airbus AS350 / H125', 'TROY 188', 'KBLI Bellingham AMB', 'patrol', 'confirmed', 'Federal patrol / interdiction (helicopter)', 'CBP AMO Bellingham AS350 (TROY 188)'),
  ('N2108J', 'A1BCFB', 'WA', 'CBP', 'Airbus AS350 / H125', 'TROY 169', 'KBLI Bellingham AMB', 'patrol', 'confirmed', 'Federal patrol / interdiction (helicopter)', 'CBP AMO Bellingham AS350 (TROY 169)'),
  ('N741C', 'A9F673', 'WA', 'CBP', 'Airbus AS350 / H125', 'TROY 170', 'KBLI Bellingham AMB', 'patrol', 'confirmed', 'Federal patrol / interdiction (helicopter)', 'CBP AMO Bellingham AS350 (TROY 170)'),
  ('N128J', 'A07232', 'WA', 'CBP', 'Beechcraft B300C MEA', 'TROY 301', 'KBLI Bellingham AMB', 'patrol', 'confirmed', 'Federal multi-enforcement aircraft (fixed-wing)', 'CBP AMO Bellingham B300C surveillance (TROY 301)'),
  ('CGNR6594', 'AE26B4', 'WA', 'USCG', 'Eurocopter MH-65E Dolphin', 'Dolphin 6594', 'KCLM Port Angeles', 'sar', 'confirmed', 'Maritime search and rescue', 'CGAS Port Angeles MH-65E (Jan 2021 delivery)'),
  ('N976HP', 'AD9AAC', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H14', 'CHP H14 / Northern Division, Redding', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N511HP', 'A665E3', 'CA', 'CHP', 'Cessna T206H Turbo Stationair', 'CHP Air11', 'CHP Air11 / Northern Division, Redding', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N159HP', 'A0EC5B', 'CA', 'CHP', 'GippsAero GA8 TC-320 Airvan', 'CHP Air13', 'CHP Air13 / Northern Division, Redding', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N617HP', 'A8097C', 'CA', 'CHP', 'Eurocopter AS350B3', 'CHP H1', 'CHP H1 / Headquarters helicopter, McClellan', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N974HP', 'AD933E', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H20', 'CHP H20 / Valley Division, Auburn', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N978HP', 'ADA21A', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H24', 'CHP H24 / Valley Division, Auburn', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N202HP', 'A19A2E', 'CA', 'CHP', 'Cessna 208B Grand Caravan', 'CHP Air21', 'CHP Air21 / Valley Division, Auburn', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N153HP', 'A0D611', 'CA', 'CHP', 'GippsAero GA8 TC-320 Airvan', 'CHP Air23', 'CHP Air23 / Valley Division, Auburn', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N981HP', 'ADAF98', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H30', 'CHP H30 / Golden Gate Division, Napa', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N982HP', 'ADB34F', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H32', 'CHP H32 / Golden Gate Division, Napa', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N137HP', 'A095EF', 'CA', 'CHP', 'GippsAero GA8 TC-320 Airvan', 'CHP Air37', 'CHP Air37 / Golden Gate Division, Napa', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N975HP', 'AD96F5', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H40', 'CHP H40 / Central Division, Fresno', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N986HP', 'ADC22B', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H42', 'CHP H42 / Central Division, Fresno', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N156HP', 'A0E136', 'CA', 'CHP', 'GippsAero GA8 TC-320 Airvan', 'CHP Air41', 'CHP Air41 / Central Division, Fresno', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N139HP', 'A09D5D', 'CA', 'CHP', 'GippsAero GA8 TC-320 Airvan', 'CHP Air43', 'CHP Air43 / Central Division, Fresno', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N983HP', 'ADB706', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H70', 'CHP H70 / Coastal Division, Paso Robles', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N443HP', 'A5567F', 'CA', 'CHP', 'Cessna T206H Turbo Stationair', 'CHP Air71', 'CHP Air71 / Coastal Division, Paso Robles', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N553HP', 'A70B4D', 'CA', 'CHP', 'Cessna T206H Turbo Stationair', 'CHP Air73', 'CHP Air73 / Coastal Division, Paso Robles', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N984HP', 'ADBABD', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H80', 'CHP H80 / Inland Division, Apple Valley', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N985HP', 'ADBE74', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H82', 'CHP H82 / Inland Division, Apple Valley', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N441HP', 'A54F11', 'CA', 'CHP', 'Cessna T206H Turbo Stationair', 'CHP Air81', 'CHP Air81 / Inland Division, Apple Valley', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N513HP', 'A66D51', 'CA', 'CHP', 'Cessna T206H Turbo Stationair', 'CHP Air83', 'CHP Air83 / Inland Division, Apple Valley', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N979HP', 'ADA5D1', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H58', 'CHP H58 / Southern Division, Fullerton', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N140HP', 'A0A36D', 'CA', 'CHP', 'GippsAero GA8 TC-320 Airvan', 'CHP Air51', 'CHP Air51 / Southern Division, Fullerton', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N988HP', 'ADC999', 'CA', 'CHP', 'Airbus AS350B3 / H125', 'CHP H60', 'CHP H60 / Border Division, Thermal', 'patrol', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N661HP', 'A8B8AD', 'CA', 'CHP', 'Cessna T206H Turbo Stationair', 'CHP Air61', 'CHP Air61 / Border Division, Thermal', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N551HP', 'A703DF', 'CA', 'CHP', 'Cessna T206H Turbo Stationair', 'CHP Air63', 'CHP Air63 / Border Division, Thermal', 'fixed_wing', 'tentative', 'Traffic enforcement', 'CHP traffic enforcement aircraft'),
  ('N60TX', 'A7C6A5', 'TX', 'Texas DPS', 'Airbus AS350B2', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N90TX', 'AC6E92', 'TX', 'Texas DPS', 'Airbus AS350B2', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N124TX', 'A0644D', 'TX', 'Texas DPS', 'Airbus AS350B2', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N204TX', 'A1A29E', 'TX', 'Texas DPS', 'Airbus AS350B2', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N405TX', 'A4C0F3', 'TX', 'Texas DPS', 'Airbus AS350B2', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N702TX', 'A95DBB', 'TX', 'Texas DPS', 'Airbus AS350B2', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N227TX', 'A1FCC1', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N2374F', 'A2256B', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N329TX', 'A3917E', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N361TX', 'A411C2', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N674TX', 'A8EC53', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N819TX', 'AB2C8A', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N824TX', 'AB4176', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N827TX', 'AB4C9B', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N844TX', 'AB9074', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N929TX', 'ACE158', 'TX', 'Texas DPS', 'Airbus AS350B3 / H125', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N145TX', 'A0B702', 'TX', 'Texas DPS', 'MBB / Airbus BK117 C-2 / EC145', null, 'Texas DPS', 'patrol', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N1727L', 'A123F3', 'TX', 'Texas DPS', 'Cessna T206H Turbo Stationair', null, 'Texas DPS', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N5271B', 'A6A56C', 'TX', 'Texas DPS', 'Cessna T206H Turbo Stationair', null, 'Texas DPS', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N219TX', 'A1DCB0', 'TX', 'Texas DPS', 'Pilatus PC-12/47E', null, 'Texas DPS', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N243TX', 'A23CE3', 'TX', 'Texas DPS', 'Pilatus PC-12/47E', null, 'Texas DPS', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N430TX', 'A524DD', 'TX', 'Texas DPS', 'Cessna 208 Caravan', null, 'Texas DPS', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N956TX', 'AD4CB0', 'TX', 'Texas DPS', 'Cessna 208 Caravan', null, 'Texas DPS', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N968TX', 'AD7B9D', 'TX', 'Texas DPS', 'Cessna 208 Caravan', null, 'Texas DPS', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Texas DPS traffic enforcement aircraft'),
  ('N25HP', 'A255E2', 'FL', 'Florida Highway Patrol', 'Cessna 182T Skylane', null, 'Florida Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Florida Highway Patrol traffic enforcement aircraft'),
  ('N611HP', 'A7F332', 'FL', 'Florida Highway Patrol', 'Cessna 182T Skylane', null, 'Florida Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Florida Highway Patrol traffic enforcement aircraft'),
  ('N267HP', 'A299BB', 'FL', 'Florida Highway Patrol', 'Cessna 172S Skyhawk', null, 'Florida Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Florida Highway Patrol traffic enforcement aircraft'),
  ('N610HP', 'A7EF7B', 'FL', 'Florida Highway Patrol', 'Cessna 172RG Cutlass RG', null, 'Florida Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Florida Highway Patrol traffic enforcement aircraft'),
  ('N706HP', 'A96B95', 'FL', 'Florida Highway Patrol', 'Cessna R182 Skylane RG', null, 'Florida Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Florida Highway Patrol traffic enforcement aircraft'),
  ('N531HP', 'A6B4E1', 'FL', 'Florida Highway Patrol', 'Cessna T206H Turbo Stationair', null, 'Florida Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Florida Highway Patrol traffic enforcement aircraft'),
  ('N773HP', 'AA74E9', 'FL', 'Florida Highway Patrol', 'Cessna T206H Turbo Stationair', null, 'Florida Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Florida Highway Patrol traffic enforcement aircraft'),
  ('N6HP', 'A7C34A', 'OH', 'Ohio State Highway Patrol', 'Cessna 182T Skylane', null, 'Ohio State Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N12HP', 'A05216', 'OH', 'Ohio State Highway Patrol', 'Cessna 182T Skylane', null, 'Ohio State Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N17HP', 'A11791', 'OH', 'Ohio State Highway Patrol', 'Cessna 182T Skylane', null, 'Ohio State Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N18HP', 'A13F10', 'OH', 'Ohio State Highway Patrol', 'Cessna 182T Skylane', null, 'Ohio State Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N19HP', 'A1668F', 'OH', 'Ohio State Highway Patrol', 'Cessna 182T Skylane', null, 'Ohio State Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N113HP', 'A03815', 'OH', 'Ohio State Highway Patrol', 'Cessna 182T Skylane', null, 'Ohio State Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N514HP', 'A67108', 'OH', 'Ohio State Highway Patrol', 'Cessna 182T Skylane', null, 'Ohio State Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N716HP', 'A99314', 'OH', 'Ohio State Highway Patrol', 'Cessna 182T Skylane', null, 'Ohio State Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N311HP', 'A34B45', 'OH', 'Ohio State Highway Patrol', 'Cessna 182S Skylane', null, 'Ohio State Highway Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N71HP', 'A97A71', 'OH', 'Ohio State Highway Patrol', 'Airbus AS350B2', null, 'Ohio State Highway Patrol', 'patrol', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N73HP', 'A9C96F', 'OH', 'Ohio State Highway Patrol', 'Airbus AS350B2', null, 'Ohio State Highway Patrol', 'patrol', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N72HP', 'A9A1F0', 'OH', 'Ohio State Highway Patrol', 'Airbus H125', null, 'Ohio State Highway Patrol', 'patrol', 'tentative', 'Traffic enforcement', 'Ohio State Highway Patrol traffic enforcement aircraft'),
  ('N202SP', 'A19B0F', 'CO', 'Colorado State Patrol', 'Cessna T182T Turbo Skylane', null, 'Colorado State Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Colorado State Patrol traffic enforcement aircraft'),
  ('N203SP', 'A19EC6', 'CO', 'Colorado State Patrol', 'Cessna T182T Turbo Skylane', null, 'Colorado State Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Colorado State Patrol traffic enforcement aircraft'),
  ('N201SP', 'A19758', 'CO', 'Colorado State Patrol', 'Pilatus PC-12/47E', null, 'Colorado State Patrol', 'fixed_wing', 'tentative', 'Traffic enforcement', 'Colorado State Patrol traffic enforcement aircraft'),
  ('N408DC', 'A4CAA7', 'CA', 'City of San Jose / Police Department', 'Kodiak 100', null, 'City of San Jose / Police Department', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'City of San Jose / Police Department local agency aircraft'),
  ('N408PD', 'A4CBA2', 'CA', 'City of San Jose / Police Department', 'Airbus AS350B3 / H125', null, 'City of San Jose / Police Department', 'patrol', 'tentative', 'Patrol / air support', 'City of San Jose / Police Department local agency aircraft'),
  ('N220PD', 'A1E24A', 'CA', 'City of Oakland / Police Department Helicopter Unit', 'McDonnell Douglas 369E', null, 'City of Oakland / Police Department Helicopter Unit', 'patrol', 'tentative', 'Patrol / air support', 'City of Oakland / Police Department Helicopter Unit local agency aircraft'),
  ('N330PD', 'A39718', 'CA', 'City of Oakland / Police Department Helicopter Unit', 'Schweizer 269C-1', null, 'City of Oakland / Police Department Helicopter Unit', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'City of Oakland / Police Department Helicopter Unit local agency aircraft'),
  ('N510PD', 'A662B8', 'CA', 'City of Oakland / Police Department Helicopter Unit', 'McDonnell Douglas 369E', null, 'City of Oakland / Police Department Helicopter Unit', 'patrol', 'tentative', 'Patrol / air support', 'City of Oakland / Police Department Helicopter Unit local agency aircraft'),
  ('N407CC', 'A4C6D7', 'CA', 'Contra Costa County', 'Bell 407', null, 'Contra Costa County', 'patrol', 'tentative', 'Patrol / air support', 'Contra Costa County local agency aircraft'),
  ('N408CC', 'A4CA8E', 'CA', 'Contra Costa County', 'Bell 407', null, 'Contra Costa County', 'patrol', 'tentative', 'Patrol / air support', 'Contra Costa County local agency aircraft'),
  ('N175JC', 'A12C8B', 'CA', 'Sacramento County Sheriff''s Office', 'Socata TBM 700', null, 'Sacramento County Sheriff''s Office', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Sacramento County Sheriff''s Office local agency aircraft'),
  ('N255SD', 'A26BA5', 'CA', 'Sacramento County Sheriff''s Office', 'Eurocopter EC120B', null, 'Sacramento County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Sacramento County Sheriff''s Office local agency aircraft'),
  ('N266SD', 'A296DB', 'CA', 'Sacramento County Sheriff''s Office', 'Eurocopter EC120B', null, 'Sacramento County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Sacramento County Sheriff''s Office local agency aircraft'),
  ('N277SD', 'A2C211', 'CA', 'Sacramento County Sheriff''s Office', 'Eurocopter EC120B', null, 'Sacramento County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Sacramento County Sheriff''s Office local agency aircraft'),
  ('N774FL', 'AA786B', 'CA', 'Sacramento County Sheriff''s Office', 'Cessna T206H', null, 'Sacramento County Sheriff''s Office', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Sacramento County Sheriff''s Office local agency aircraft'),
  ('N911GC', 'AC9AFB', 'CA', 'Sacramento County Sheriff''s Office', 'Bell UH-1H', null, 'Sacramento County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Sacramento County Sheriff''s Office local agency aircraft'),
  ('N911RY', 'AC9BF0', 'CA', 'Sacramento County Sheriff''s Office', 'Bell UH-1H', null, 'Sacramento County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Sacramento County Sheriff''s Office local agency aircraft'),
  ('N920FC', 'ACBEAA', 'CA', 'Fresno County Sheriff / County of Fresno', 'MD Helicopters 369FF', null, 'Fresno County Sheriff / County of Fresno', 'patrol', 'tentative', 'Patrol / air support', 'Fresno County Sheriff / County of Fresno local agency aircraft'),
  ('N921SD', 'ACC375', 'CA', 'Fresno County Sheriff / County of Fresno', 'McDonnell Douglas 369E', null, 'Fresno County Sheriff / County of Fresno', 'patrol', 'tentative', 'Patrol / air support', 'Fresno County Sheriff / County of Fresno local agency aircraft'),
  ('N922SD', 'ACC72C', 'CA', 'Fresno County Sheriff / County of Fresno', 'McDonnell Douglas 369E', null, 'Fresno County Sheriff / County of Fresno', 'patrol', 'tentative', 'Patrol / air support', 'Fresno County Sheriff / County of Fresno local agency aircraft'),
  ('N514JD', 'A67117', 'CA', 'City of Fresno', 'Eurocopter EC120B', null, 'City of Fresno', 'patrol', 'tentative', 'Patrol / air support', 'City of Fresno local agency aircraft'),
  ('N524MW', 'A698F2', 'CA', 'City of Fresno', 'Eurocopter EC120B', null, 'City of Fresno', 'patrol', 'tentative', 'Patrol / air support', 'City of Fresno local agency aircraft'),
  ('N534PD', 'A6C092', 'CA', 'City of Fresno / Fresno Police Department', 'Airbus AS350B3 / H125', null, 'City of Fresno / Fresno Police Department', 'patrol', 'tentative', 'Patrol / air support', 'City of Fresno / Fresno Police Department local agency aircraft'),
  ('N189JC', 'A162E6', 'CA', 'Tulare County Sheriff', 'Textron Aviation / Cessna T206H', null, 'Tulare County Sheriff', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Tulare County Sheriff local agency aircraft'),
  ('N297E', 'A30FDF', 'CA', 'Kern County Sheriff''s Department / County of Kern', 'Hughes 369E', null, 'Kern County Sheriff''s Department / County of Kern', 'patrol', 'tentative', 'Patrol / air support', 'Kern County Sheriff''s Department / County of Kern local agency aircraft'),
  ('N35438', 'A3F68B', 'CA', 'Kern County Sheriff''s Department', 'Cessna T206H', null, 'Kern County Sheriff''s Department', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Kern County Sheriff''s Department local agency aircraft'),
  ('N397E', 'A49D2E', 'CA', 'Kern County Sheriff''s Department', 'Bell OH-58A', null, 'Kern County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Kern County Sheriff''s Department local agency aircraft'),
  ('N497E', 'A62A7D', 'CA', 'Kern County Sheriff''s Department', 'Bell OH-58A', null, 'Kern County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Kern County Sheriff''s Department local agency aircraft'),
  ('N597E', 'A7B7CC', 'CA', 'Kern County Sheriff''s Department / County of Kern', 'Bell UH-1H', null, 'Kern County Sheriff''s Department / County of Kern', 'patrol', 'tentative', 'Patrol / air support', 'Kern County Sheriff''s Department / County of Kern local agency aircraft'),
  ('N911KC', 'AC9B46', 'CA', 'Kern County Sheriff''s Department / County of Kern', 'Rockwell International 690A', null, 'Kern County Sheriff''s Department / County of Kern', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Kern County Sheriff''s Department / County of Kern local agency aircraft'),
  ('N912KC', 'AC9EFD', 'CA', 'Kern County Sheriff''s Department', 'Airbus AS350B3', null, 'Kern County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Kern County Sheriff''s Department local agency aircraft'),
  ('N913KC', 'ACA2B4', 'CA', 'Kern County Sheriff''s Department', 'Airbus AS350B3', null, 'Kern County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Kern County Sheriff''s Department local agency aircraft'),
  ('N737ZA', 'A9E74C', 'CA', 'County of Santa Cruz', 'Cessna 172N', null, 'County of Santa Cruz', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'County of Santa Cruz local agency aircraft'),
  ('N991YC', 'ADD883', 'CA', 'City of Sacramento', 'Bell OH-58A', null, 'City of Sacramento', 'patrol', 'tentative', 'Patrol / air support', 'City of Sacramento local agency aircraft'),
  ('N213PF', 'A1C5F2', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N221LA', 'A1E5B3', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N223LA', 'A1ED21', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N224LA', 'A1F0D8', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N225LA', 'A1F48F', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N226LA', 'A1F846', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N228LA', 'A1FFB4', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Eurocopter AS350B2', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N230LA', 'A2097B', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N232LA', 'A210E9', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N233LA', 'A214A0', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N267LA', 'A299F9', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N472LA', 'A5C983', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Airbus AS350B3 / H125', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N665PD', 'A8C815', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Eurocopter AS350B2', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N913WB', 'ACA3C6', 'CA', 'Los Angeles Police Department / LAPD Air Support Division', 'Eurocopter AS350B2', null, 'Los Angeles Police Department / LAPD Air Support Division', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles Police Department / LAPD Air Support Division local agency aircraft'),
  ('N104RC', 'A0150A', 'CA', 'Los Angeles County Sheriff''s Department', 'McDonnell Douglas 369E', null, 'Los Angeles County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department local agency aircraft'),
  ('N535JP', 'A6C3D6', 'CA', 'Los Angeles County Sheriff''s Department', 'McDonnell Douglas 369E', null, 'Los Angeles County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department local agency aircraft'),
  ('N6330C', 'A84B3C', 'CA', 'Los Angeles County Sheriff''s Department', 'Cessna 210N', null, 'Los Angeles County Sheriff''s Department', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Los Angeles County Sheriff''s Department local agency aircraft'),
  ('N732WQ', 'A9D47C', 'CA', 'Los Angeles County Sheriff''s Department', 'Cessna T210M', null, 'Los Angeles County Sheriff''s Department', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Los Angeles County Sheriff''s Department local agency aircraft'),
  ('N950JE', 'AD3574', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Airbus / Eurocopter AS332L1', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N950LA', 'AD35A2', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N951LA', 'AD3959', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N951LB', 'AD395A', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Airbus / Eurocopter AS332L1', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N952JH', 'AD3CE5', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Airbus / Eurocopter AS332L1', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N953LA', 'AD40C7', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N954LA', 'AD447E', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N955LA', 'AD4835', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N956LA', 'AD4BEC', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N957LA', 'AD4FA3', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N958LA', 'AD535A', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N959LA', 'AD5711', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N960LA', 'AD5D21', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N961LA', 'AD60D8', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N961SD', 'AD6171', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N962LA', 'AD648F', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N963SD', 'AD68DF', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N966SD', 'AD7404', 'CA', 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'Eurocopter AS350B2', null, 'Los Angeles County Sheriff''s Department / County of Los Angeles', 'patrol', 'tentative', 'Patrol / air support', 'Los Angeles County Sheriff''s Department / County of Los Angeles local agency aircraft'),
  ('N166PD', 'A10941', 'CA', 'City of Fontana', 'Robinson R66', null, 'City of Fontana', 'patrol', 'tentative', 'Patrol / air support', 'City of Fontana local agency aircraft'),
  ('N462PD', 'A5A252', 'CA', 'City of Fontana', 'Robinson R66', null, 'City of Fontana', 'patrol', 'tentative', 'Patrol / air support', 'City of Fontana local agency aircraft'),
  ('N641EG', 'A8695D', 'CA', 'City of Fontana', 'American Eurocopter AS350B2', null, 'City of Fontana', 'patrol', 'tentative', 'Patrol / air support', 'City of Fontana local agency aircraft'),
  ('N226PD', 'A1F894', 'CA', 'Anaheim Police Department', 'Eurocopter AS350B2', null, 'Anaheim Police Department', 'patrol', 'tentative', 'Patrol / air support', 'Anaheim Police Department local agency aircraft'),
  ('N28LB', 'A2CC9E', 'CA', 'City of Long Beach', 'Eurocopter AS350B2', null, 'City of Long Beach', 'patrol', 'tentative', 'Patrol / air support', 'City of Long Beach local agency aircraft'),
  ('N29LB', 'A2F41D', 'CA', 'City of Long Beach', 'Eurocopter AS350B2', null, 'City of Long Beach', 'patrol', 'tentative', 'Patrol / air support', 'City of Long Beach local agency aircraft'),
  ('N9495F', 'AD31A4', 'CA', 'City of Long Beach', 'Hughes 269B', null, 'City of Long Beach', 'patrol', 'tentative', 'Patrol / air support', 'City of Long Beach local agency aircraft'),
  ('N9549F', 'AD471C', 'CA', 'City of Long Beach', 'Hughes 269B', null, 'City of Long Beach', 'patrol', 'tentative', 'Patrol / air support', 'City of Long Beach local agency aircraft'),
  ('N165PW', 'A1059B', 'CA', 'San Bernardino County Sheriff''s Department', 'GippsAero GA8 TC-320', null, 'San Bernardino County Sheriff''s Department', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N214SB', 'A1C9F0', 'CA', 'San Bernardino County Sheriff''s Department', 'Beech A200', null, 'San Bernardino County Sheriff''s Department', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N265PW', 'A292EA', 'CA', 'San Bernardino County Sheriff''s Department', 'GippsAero GA8 TC-320', null, 'San Bernardino County Sheriff''s Department', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N305SB', 'A33377', 'CA', 'San Bernardino County Sheriff''s Department', 'Bell UH-1H', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N307SB', 'A33AE5', 'CA', 'San Bernardino County Sheriff''s Department', 'Bell 212', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N308SB', 'A33E9C', 'CA', 'San Bernardino County Sheriff''s Department', 'Bell 412EP', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N309SB', 'A34253', 'CA', 'San Bernardino County Sheriff''s Department', 'Bell UH-1H', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N625SB', 'A82A62', 'CA', 'San Bernardino County Sheriff''s Department', 'MD Helicopters 600N', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N631SB', 'A84305', 'CA', 'San Bernardino County Sheriff''s Department', 'Airbus AS350B3', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N803SB', 'AAEE94', 'CA', 'San Bernardino County Sheriff''s Department', 'McDonnell Douglas 369E', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N831SB', 'AB5DA3', 'CA', 'San Bernardino County Sheriff''s Department', 'Airbus AS350B3', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N832SB', 'AB615A', 'CA', 'San Bernardino County Sheriff''s Department', 'Airbus AS350B3', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N833SB', 'AB6511', 'CA', 'San Bernardino County Sheriff''s Department', 'Airbus AS350B3', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N834SB', 'AB68C8', 'CA', 'San Bernardino County Sheriff''s Department', 'Airbus AS350B3', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N835SB', 'AB6C7F', 'CA', 'San Bernardino County Sheriff''s Department', 'Airbus AS350B3', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N836SB', 'AB7036', 'CA', 'San Bernardino County Sheriff''s Department', 'Airbus AS350B3', null, 'San Bernardino County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Bernardino County Sheriff''s Department local agency aircraft'),
  ('N313DP', 'A3524F', 'CA', 'San Diego County Sheriff''s Department', 'Bell 407', null, 'San Diego County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Diego County Sheriff''s Department local agency aircraft'),
  ('N319MW', 'A36968', 'CA', 'San Diego County Sheriff''s Department', 'Bell 407', null, 'San Diego County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Diego County Sheriff''s Department local agency aircraft'),
  ('N670PC', 'A8DD00', 'CA', 'San Diego County Sheriff''s Department', 'Bell 407', null, 'San Diego County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Diego County Sheriff''s Department local agency aircraft'),
  ('N709WG', 'A977F8', 'CA', 'San Diego County Sheriff''s Department', 'Bell 407', null, 'San Diego County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Diego County Sheriff''s Department local agency aircraft'),
  ('N989RL', 'ADCE15', 'CA', 'San Diego County Sheriff''s Department', 'Bell 412EP', null, 'San Diego County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'San Diego County Sheriff''s Department local agency aircraft'),
  ('N881SD', 'AC2320', 'CA', 'City of San Diego / Police Air Support Unit', 'Airbus AS350B3', null, 'City of San Diego / Police Air Support Unit', 'patrol', 'tentative', 'Patrol / air support', 'City of San Diego / Police Air Support Unit local agency aircraft'),
  ('N882SD', 'AC26D7', 'CA', 'City of San Diego / Police Air Support Unit', 'Airbus AS350B3', null, 'City of San Diego / Police Air Support Unit', 'patrol', 'tentative', 'Patrol / air support', 'City of San Diego / Police Air Support Unit local agency aircraft'),
  ('N883SD', 'AC2A8E', 'CA', 'City of San Diego / Police Air Support Unit', 'Airbus AS350B3', null, 'City of San Diego / Police Air Support Unit', 'patrol', 'tentative', 'Patrol / air support', 'City of San Diego / Police Air Support Unit local agency aircraft'),
  ('N884SD', 'AC2E45', 'CA', 'City of San Diego / Police Air Support Unit', 'Airbus AS350B3', null, 'City of San Diego / Police Air Support Unit', 'patrol', 'tentative', 'Patrol / air support', 'City of San Diego / Police Air Support Unit local agency aircraft'),
  ('N181SD', 'A145F7', 'CA', 'Orange County Sheriff''s Department / RNSP', 'Bell UH-1H', null, 'Orange County Sheriff''s Department / RNSP', 'patrol', 'tentative', 'Patrol / air support', 'Orange County Sheriff''s Department / RNSP local agency aircraft'),
  ('N183SD', 'A14D65', 'CA', 'Orange County Sheriff''s Department / RNSP', 'Airbus AS350B3', null, 'Orange County Sheriff''s Department / RNSP', 'patrol', 'tentative', 'Patrol / air support', 'Orange County Sheriff''s Department / RNSP local agency aircraft'),
  ('N185SD', 'A154D3', 'CA', 'Orange County Sheriff''s Department / RNSP', 'Airbus AS350B3', null, 'Orange County Sheriff''s Department / RNSP', 'patrol', 'tentative', 'Patrol / air support', 'Orange County Sheriff''s Department / RNSP local agency aircraft'),
  ('N186SD', 'A1588A', 'CA', 'Orange County Sheriff''s Department / RNSP', 'Bell UH-1H', null, 'Orange County Sheriff''s Department / RNSP', 'patrol', 'tentative', 'Patrol / air support', 'Orange County Sheriff''s Department / RNSP local agency aircraft'),
  ('N6045C', 'A7D925', 'CA', 'Orange County Sheriff''s Department / RNSP', 'Cessna T206H', null, 'Orange County Sheriff''s Department / RNSP', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Orange County Sheriff''s Department / RNSP local agency aircraft'),
  ('N960RN', 'AD5DAA', 'CA', 'Orange County Sheriff''s Department / RNSP', 'GippsAero GA8 TC-320', null, 'Orange County Sheriff''s Department / RNSP', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Orange County Sheriff''s Department / RNSP local agency aircraft'),
  ('N893RC', 'AC51F3', 'CA', 'Riverside County Sheriff''s Office', 'Pilatus PC-12/47E', null, 'Riverside County Sheriff''s Office', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Riverside County Sheriff''s Office local agency aircraft'),
  ('N205SD', 'A1A62A', 'CA', 'Ventura County Sheriff''s Department', 'Bell HH-1H', null, 'Ventura County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Ventura County Sheriff''s Department local agency aircraft'),
  ('N205VC', 'A1A674', 'CA', 'Ventura County Sheriff''s Department', 'Bell 205B', null, 'Ventura County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Ventura County Sheriff''s Department local agency aircraft'),
  ('N206VC', 'A1AA2B', 'CA', 'Ventura County Sheriff''s Department', 'Bell 206L-1', null, 'Ventura County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Ventura County Sheriff''s Department local agency aircraft'),
  ('N32240', 'A378BB', 'CA', 'Ventura County Sheriff''s Department', 'Bell 205A-1', null, 'Ventura County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Ventura County Sheriff''s Department local agency aircraft'),
  ('N911VC', 'AC9C40', 'CA', 'Ventura County Sheriff''s Department', 'Bell 206L-3', null, 'Ventura County Sheriff''s Department', 'patrol', 'tentative', 'Patrol / air support', 'Ventura County Sheriff''s Department local agency aircraft'),
  ('N371DM', 'A437D9', 'CA', 'City of Bakersfield', 'American Champion 8GCBC', null, 'City of Bakersfield', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'City of Bakersfield local agency aircraft'),
  ('N47PS', 'A5C017', 'CA', 'City of Palm Springs', 'Cessna 182P', null, 'City of Palm Springs', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'City of Palm Springs local agency aircraft'),
  ('N1576F', 'A0E760', 'TX', 'City of Houston Police Department', 'McDonnell Douglas 369E', null, 'City of Houston Police Department', 'patrol', 'tentative', 'Patrol / air support', 'City of Houston Police Department local agency aircraft'),
  ('N8372F', 'AB74FF', 'TX', 'City of Houston Police Department', 'McDonnell Douglas 369E', null, 'City of Houston Police Department', 'patrol', 'tentative', 'Patrol / air support', 'City of Houston Police Department local agency aircraft'),
  ('N9298F', 'ACE30F', 'TX', 'City of Houston Police Department', 'Hughes 269C', null, 'City of Houston Police Department', 'patrol', 'tentative', 'Patrol / air support', 'City of Houston Police Department local agency aircraft'),
  ('N9686F', 'AD7D0E', 'TX', 'City of Houston Police Department', 'Hughes 269C', null, 'City of Houston Police Department', 'patrol', 'tentative', 'Patrol / air support', 'City of Houston Police Department local agency aircraft'),
  ('N125AP', 'A06653', 'TX', 'Austin Police Department', 'Airbus AS350B3', null, 'Austin Police Department', 'patrol', 'tentative', 'Patrol / air support', 'Austin Police Department local agency aircraft'),
  ('N21475', 'A1CBC9', 'TX', 'Austin Police Department', 'Cessna 182P', null, 'Austin Police Department', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Austin Police Department local agency aircraft'),
  ('N6227', 'A820F8', 'TX', 'Austin Police Department', 'Airbus AS350B3', null, 'Austin Police Department', 'patrol', 'tentative', 'Patrol / air support', 'Austin Police Department local agency aircraft'),
  ('N67662', 'A8F547', 'TX', 'Austin Police Department', 'Bell 206B', null, 'Austin Police Department', 'patrol', 'tentative', 'Patrol / air support', 'Austin Police Department local agency aircraft'),
  ('N917FW', 'ACB13E', 'TX', 'Fort Worth Police Department', 'Bell 206B', null, 'Fort Worth Police Department', 'patrol', 'tentative', 'Patrol / air support', 'Fort Worth Police Department local agency aircraft'),
  ('N911FW', 'AC9AF4', 'TX', 'Fort Worth Police Department', 'Bell 505', null, 'Fort Worth Police Department', 'patrol', 'tentative', 'Patrol / air support', 'Fort Worth Police Department local agency aircraft'),
  ('N206FW', 'A1A8DF', 'TX', 'Fort Worth Police Department', 'Bell 206B', null, 'Fort Worth Police Department', 'patrol', 'tentative', 'Patrol / air support', 'Fort Worth Police Department local agency aircraft'),
  ('N505FW', 'A64D15', 'TX', 'Fort Worth Police Department', 'Bell 505', null, 'Fort Worth Police Department', 'patrol', 'tentative', 'Patrol / air support', 'Fort Worth Police Department local agency aircraft'),
  ('N111NK', 'A03120', 'TX', 'San Antonio Police Department', 'Airbus AS350B3', null, 'San Antonio Police Department', 'patrol', 'tentative', 'Patrol / air support', 'San Antonio Police Department local agency aircraft'),
  ('N820PM', 'AB322C', 'TX', 'San Antonio Police Department', 'Eurocopter EC120B', null, 'San Antonio Police Department', 'patrol', 'tentative', 'Patrol / air support', 'San Antonio Police Department local agency aircraft'),
  ('N312SD', 'A34FD3', 'TX', 'Harris County Sheriff''s Office', 'Airbus AS350B3', null, 'Harris County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Harris County Sheriff''s Office local agency aircraft'),
  ('N731SD', 'A9D056', 'TX', 'Harris County Sheriff''s Office', 'Bell OH-58A', null, 'Harris County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Harris County Sheriff''s Office local agency aircraft'),
  ('N915SD', 'ACAAD2', 'TX', 'Harris County Sheriff''s Office', 'Bell OH-58A', null, 'Harris County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Harris County Sheriff''s Office local agency aircraft'),
  ('N71LC', 'A97AB1', 'FL', 'Lee County Sheriff''s Office', 'Airbus / Eurocopter AS350B3', null, 'Lee County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Lee County Sheriff''s Office local agency aircraft'),
  ('N72LC', 'A9A230', 'FL', 'Lee County Sheriff''s Office', 'Airbus / Eurocopter AS350B2', null, 'Lee County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Lee County Sheriff''s Office local agency aircraft'),
  ('N73LC', 'A9C9AF', 'FL', 'Lee County Sheriff''s Office', 'Airbus / Eurocopter AS350B3', null, 'Lee County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Lee County Sheriff''s Office local agency aircraft'),
  ('N74LC', 'A9F12E', 'FL', 'Lee County Sheriff''s Office', 'Cessna T210L', null, 'Lee County Sheriff''s Office', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Lee County Sheriff''s Office local agency aircraft'),
  ('N407KB', 'A4C785', 'FL', 'Orange County Sheriff''s Office', 'Bell 407', null, 'Orange County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Orange County Sheriff''s Office local agency aircraft'),
  ('N407LM', 'A4C7A8', 'FL', 'Orange County Sheriff''s Office', 'Bell 407', null, 'Orange County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Orange County Sheriff''s Office local agency aircraft'),
  ('N407NL', 'A4C7D9', 'FL', 'Orange County Sheriff''s Office', 'Bell 407', null, 'Orange County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Orange County Sheriff''s Office local agency aircraft'),
  ('N481RC', 'A5EDCA', 'FL', 'Orange County Sheriff''s Office', 'Bell 206L-3', null, 'Orange County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Orange County Sheriff''s Office local agency aircraft'),
  ('N552CH', 'A70713', 'FL', 'Orange County Sheriff''s Office', 'Bell 407', null, 'Orange County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Orange County Sheriff''s Office local agency aircraft'),
  ('N866DM', 'ABE578', 'FL', 'Orange County Sheriff''s Office', 'Cessna T206H', null, 'Orange County Sheriff''s Office', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Orange County Sheriff''s Office local agency aircraft'),
  ('N103JP', 'A010AF', 'FL', 'Jacksonville Sheriff''s Office / City of Jacksonville', 'Bell 407', null, 'Jacksonville Sheriff''s Office / City of Jacksonville', 'patrol', 'tentative', 'Patrol / air support', 'Jacksonville Sheriff''s Office / City of Jacksonville local agency aircraft'),
  ('N311JP', 'A34B5E', 'FL', 'Jacksonville Sheriff''s Office / City of Jacksonville', 'Bell OH-58A', null, 'Jacksonville Sheriff''s Office / City of Jacksonville', 'patrol', 'tentative', 'Patrol / air support', 'Jacksonville Sheriff''s Office / City of Jacksonville local agency aircraft'),
  ('N312JP', 'A34F15', 'FL', 'Jacksonville Sheriff''s Office / City of Jacksonville', 'Bell 206B', null, 'Jacksonville Sheriff''s Office / City of Jacksonville', 'patrol', 'tentative', 'Patrol / air support', 'Jacksonville Sheriff''s Office / City of Jacksonville local agency aircraft'),
  ('N313JP', 'A352CC', 'FL', 'Jacksonville Sheriff''s Office / City of Jacksonville', 'Bell 206B-III / MD 369E', null, 'Jacksonville Sheriff''s Office / City of Jacksonville', 'patrol', 'tentative', 'Patrol / air support', 'Jacksonville Sheriff''s Office / City of Jacksonville local agency aircraft'),
  ('N314JP', 'A35683', 'FL', 'Jacksonville Sheriff''s Office / City of Jacksonville', 'Bell 407', null, 'Jacksonville Sheriff''s Office / City of Jacksonville', 'patrol', 'tentative', 'Patrol / air support', 'Jacksonville Sheriff''s Office / City of Jacksonville local agency aircraft'),
  ('N317JP', 'A361A8', 'FL', 'Jacksonville Sheriff''s Office / City of Jacksonville', 'Bell 206B', null, 'Jacksonville Sheriff''s Office / City of Jacksonville', 'patrol', 'tentative', 'Patrol / air support', 'Jacksonville Sheriff''s Office / City of Jacksonville local agency aircraft'),
  ('N92JP', 'ACBCA7', 'FL', 'Jacksonville Sheriff''s Office / City of Jacksonville', 'Bell 407', null, 'Jacksonville Sheriff''s Office / City of Jacksonville', 'patrol', 'tentative', 'Patrol / air support', 'Jacksonville Sheriff''s Office / City of Jacksonville local agency aircraft'),
  ('N109BC', 'A0263F', 'FL', 'Broward County Sheriff''s Office', 'Eurocopter EC135T1', null, 'Broward County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Broward County Sheriff''s Office local agency aircraft'),
  ('N257BC', 'A2719B', 'FL', 'Broward County Sheriff''s Office', 'Eurocopter EC135T2+', null, 'Broward County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Broward County Sheriff''s Office local agency aircraft'),
  ('N265BC', 'A291AC', 'FL', 'Broward County Sheriff''s Office', 'Airbus MBB-BK117 D-3 / H145', null, 'Broward County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Broward County Sheriff''s Office local agency aircraft'),
  ('N268BC', 'A29CD1', 'FL', 'Broward County Sheriff''s Office', 'Airbus MBB-BK117 D-3 / H145', null, 'Broward County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Broward County Sheriff''s Office local agency aircraft'),
  ('N781BC', 'AA9459', 'FL', 'Broward County Sheriff''s Office', 'Airbus AS350B3', null, 'Broward County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Broward County Sheriff''s Office local agency aircraft'),
  ('N782BC', 'AA9810', 'FL', 'Broward County Sheriff''s Office', 'Airbus AS350B3', null, 'Broward County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Broward County Sheriff''s Office local agency aircraft'),
  ('N783BC', 'AA9BC7', 'FL', 'Broward County Sheriff''s Office', 'Airbus AS350B3', null, 'Broward County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Broward County Sheriff''s Office local agency aircraft'),
  ('N101TN', 'A00A21', 'FL', 'Hillsborough County Sheriff''s Office', 'Textron Aviation 208 / Cessna 208 Caravan', null, 'Hillsborough County Sheriff''s Office', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Hillsborough County Sheriff''s Office local agency aircraft'),
  ('N227ND', 'A1FC32', 'FL', 'Hillsborough County Sheriff''s Office', 'Airbus AS350B3', null, 'Hillsborough County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Hillsborough County Sheriff''s Office local agency aircraft'),
  ('N245HC', 'A24344', 'FL', 'Hillsborough County Sheriff''s Office', 'Pilatus PC-12/47E', null, 'Hillsborough County Sheriff''s Office', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Hillsborough County Sheriff''s Office local agency aircraft'),
  ('N413JM', 'A4E019', 'FL', 'Hillsborough County Sheriff''s Office', 'Airbus AS350B3', null, 'Hillsborough County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Hillsborough County Sheriff''s Office local agency aircraft'),
  ('N717CD', 'A99644', 'FL', 'Hillsborough County Sheriff''s Office', 'Airbus AS350B3', null, 'Hillsborough County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Hillsborough County Sheriff''s Office local agency aircraft'),
  ('N911DG', 'AC9AB4', 'FL', 'Hillsborough County Sheriff''s Office', 'Airbus AS350B3', null, 'Hillsborough County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Hillsborough County Sheriff''s Office local agency aircraft'),
  ('N1SD', 'A00196', 'FL', 'Pinellas County Sheriff''s Office / Pinellas County', 'Airbus AS350B2', null, 'Pinellas County Sheriff''s Office / Pinellas County', 'patrol', 'tentative', 'Patrol / air support', 'Pinellas County Sheriff''s Office / Pinellas County local agency aircraft'),
  ('N2SD', 'A18EE5', 'FL', 'Pinellas County Sheriff''s Office / Pinellas County', 'Eurocopter AS350B2', null, 'Pinellas County Sheriff''s Office / Pinellas County', 'patrol', 'tentative', 'Patrol / air support', 'Pinellas County Sheriff''s Office / Pinellas County local agency aircraft'),
  ('N43SD', 'A52259', 'FL', 'Pinellas County Sheriff''s Office / Pinellas County', 'Airbus AS350B3', null, 'Pinellas County Sheriff''s Office / Pinellas County', 'patrol', 'tentative', 'Patrol / air support', 'Pinellas County Sheriff''s Office / Pinellas County local agency aircraft'),
  ('N14806', 'A0C2DF', 'FL', 'Pinellas County Sheriff''s Office / Pinellas County', 'Airbus AS350B3', null, 'Pinellas County Sheriff''s Office / Pinellas County', 'patrol', 'tentative', 'Patrol / air support', 'Pinellas County Sheriff''s Office / Pinellas County local agency aircraft'),
  ('N58501', 'A78AED', 'FL', 'Pinellas County Sheriff''s Office / Pinellas County', 'Cessna 208B', null, 'Pinellas County Sheriff''s Office / Pinellas County', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Pinellas County Sheriff''s Office / Pinellas County local agency aircraft'),
  ('N518DS', 'A67F83', 'FL', 'Volusia Sheriff''s Office', 'Bell 407', null, 'Volusia Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Volusia Sheriff''s Office local agency aircraft'),
  ('N618DS', 'A80CD2', 'FL', 'Volusia Sheriff''s Office', 'Bell 407', null, 'Volusia Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Volusia Sheriff''s Office local agency aircraft'),
  ('N718DS', 'A99A21', 'FL', 'Volusia Sheriff''s Office', 'Bell 407', null, 'Volusia Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Volusia Sheriff''s Office local agency aircraft'),
  ('N401H', 'A4B107', 'FL', 'St. Johns County Sheriff''s Office', 'Bell 407', null, 'St. Johns County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'St. Johns County Sheriff''s Office local agency aircraft'),
  ('N506MC', 'A65150', 'FL', 'Manatee County Sheriff''s Office', 'Bell 407', null, 'Manatee County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Manatee County Sheriff''s Office local agency aircraft'),
  ('N175SC', 'A12D53', 'FL', 'Seminole County Sheriff''s Office', 'Airbus H125 / AS350B3-type', null, 'Seminole County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Seminole County Sheriff''s Office local agency aircraft'),
  ('N176SC', 'A1310A', 'FL', 'Seminole County Sheriff''s Office', 'Airbus H125 / AS350B3-type', null, 'Seminole County Sheriff''s Office', 'patrol', 'tentative', 'Patrol / air support', 'Seminole County Sheriff''s Office local agency aircraft'),
  ('N401MP', 'A4B179', 'FL', 'Miami-Dade Police Department', 'Cessna P210N', null, 'Miami-Dade Police Department', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Miami-Dade Police Department local agency aircraft'),
  ('N772GJ', 'AA7114', 'FL', 'Polk County Sheriff''s Office', 'Kodiak 100', null, 'Polk County Sheriff''s Office', 'fixed_wing', 'tentative', 'Law enforcement / surveillance', 'Polk County Sheriff''s Office local agency aircraft'),
  ('N551CP', 'A70362', 'OH', 'City of Columbus / Division of Police', 'MD Helicopters 369FF', null, 'City of Columbus / Division of Police', 'patrol', 'tentative', 'Patrol / air support', 'City of Columbus / Division of Police local agency aircraft'),
  ('N552CP', 'A70719', 'OH', 'City of Columbus / Division of Police', 'Bell 505', null, 'City of Columbus / Division of Police', 'patrol', 'tentative', 'Patrol / air support', 'City of Columbus / Division of Police local agency aircraft'),
  ('N553CP', 'A70AD0', 'OH', 'City of Columbus / Division of Police', 'MD Helicopters 369FF', null, 'City of Columbus / Division of Police', 'patrol', 'tentative', 'Patrol / air support', 'City of Columbus / Division of Police local agency aircraft'),
  ('N556CP', 'A715F5', 'OH', 'City of Columbus / Division of Police', 'MD Helicopters 369FF', null, 'City of Columbus / Division of Police', 'patrol', 'tentative', 'Patrol / air support', 'City of Columbus / Division of Police local agency aircraft'),
  ('N557CP', 'A719AC', 'OH', 'City of Columbus / Division of Police', 'MD Helicopters 369FF', null, 'City of Columbus / Division of Police', 'patrol', 'tentative', 'Patrol / air support', 'City of Columbus / Division of Police local agency aircraft'),
  ('N559CP', 'A7211A', 'OH', 'City of Columbus / Division of Police', 'Bell 505', null, 'City of Columbus / Division of Police', 'patrol', 'tentative', 'Patrol / air support', 'City of Columbus / Division of Police local agency aircraft'),
  ('N951CP', 'AD389E', 'OH', 'City of Cleveland / Cleveland Division of Police', 'McDonnell Douglas 369E', null, 'City of Cleveland / Cleveland Division of Police', 'patrol', 'tentative', 'Patrol / air support', 'City of Cleveland / Cleveland Division of Police local agency aircraft'),
  ('N952CP', 'AD3C55', 'OH', 'City of Cleveland / Cleveland Division of Police', 'McDonnell Douglas 369E', null, 'City of Cleveland / Cleveland Division of Police', 'patrol', 'tentative', 'Patrol / air support', 'City of Cleveland / Cleveland Division of Police local agency aircraft'),
  ('N720DP', 'A9A3E5', 'CO', 'City and County of Denver / Denver Police', 'Bell 407', null, 'City and County of Denver / Denver Police', 'patrol', 'tentative', 'Patrol / air support', 'City and County of Denver / Denver Police local agency aircraft')
on conflict (tail) do update set
  icao24 = excluded.icao24,
  home_state_code = excluded.home_state_code,
  operator = excluded.operator,
  model = excluded.model,
  nickname = excluded.nickname,
  base = excluded.base,
  role = excluded.role,
  role_confidence = excluded.role_confidence,
  role_description = excluded.role_description,
  role_note = excluded.role_note,
  active = true,
  updated_at = now();

insert into public.aircraft_performance_profiles (
  aircraft_id,
  nominal_endurance_min,
  reserve_min,
  source_note,
  updated_at
)
select
  aircraft.id,
  durations.nominal_endurance_min,
  30,
  'Catalog endurance estimate; verify against an authoritative aircraft source.',
  now()
from (
  values
  ('N305DK', 420),
  ('N305RC', 360),
  ('N2446X', 420),
  ('N102LP', 360),
  ('N3532K', 360),
  ('N207HB', 372),
  ('N422CT', 240),
  ('N407KS', 240),
  ('N411KS', 189),
  ('N790RJ', 150),
  ('N67817', 189),
  ('N67880', 189),
  ('N78906', 189),
  ('N9446P', 282),
  ('N815SC', 150),
  ('N976HP', 240),
  ('N511HP', 285),
  ('N159HP', 390),
  ('N617HP', 240),
  ('N974HP', 240),
  ('N978HP', 240),
  ('N202HP', 300),
  ('N153HP', 390),
  ('N981HP', 240),
  ('N982HP', 240),
  ('N137HP', 390),
  ('N975HP', 240),
  ('N986HP', 240),
  ('N156HP', 390),
  ('N139HP', 390),
  ('N983HP', 240),
  ('N443HP', 285),
  ('N553HP', 285),
  ('N984HP', 240),
  ('N985HP', 240),
  ('N441HP', 285),
  ('N513HP', 285),
  ('N979HP', 240),
  ('N140HP', 390),
  ('N988HP', 240),
  ('N661HP', 285),
  ('N551HP', 285),
  ('N60TX', 240),
  ('N90TX', 240),
  ('N124TX', 240),
  ('N204TX', 240),
  ('N405TX', 240),
  ('N702TX', 240),
  ('N227TX', 240),
  ('N2374F', 240),
  ('N329TX', 240),
  ('N361TX', 240),
  ('N674TX', 240),
  ('N819TX', 240),
  ('N824TX', 240),
  ('N827TX', 240),
  ('N844TX', 240),
  ('N929TX', 240),
  ('N145TX', 210),
  ('N1727L', 285),
  ('N5271B', 285),
  ('N219TX', 420),
  ('N243TX', 420),
  ('N430TX', 330),
  ('N956TX', 330),
  ('N968TX', 330),
  ('N25HP', 330),
  ('N611HP', 330),
  ('N267HP', 300),
  ('N610HP', 300),
  ('N706HP', 300),
  ('N531HP', 285),
  ('N773HP', 285),
  ('N6HP', 330),
  ('N12HP', 330),
  ('N17HP', 330),
  ('N18HP', 330),
  ('N19HP', 330),
  ('N113HP', 330),
  ('N514HP', 330),
  ('N716HP', 330),
  ('N311HP', 330),
  ('N71HP', 240),
  ('N73HP', 240),
  ('N72HP', 240),
  ('N202SP', 285),
  ('N203SP', 285),
  ('N201SP', 420),
  ('N408DC', 594),
  ('N408PD', 267),
  ('N220PD', 150),
  ('N330PD', 210),
  ('N510PD', 150),
  ('N407CC', 275),
  ('N408CC', 275),
  ('N175JC', 300),
  ('N255SD', 272),
  ('N266SD', 272),
  ('N277SD', 272),
  ('N774FL', 285),
  ('N911GC', 144),
  ('N911RY', 144),
  ('N920FC', 150),
  ('N921SD', 150),
  ('N922SD', 150),
  ('N514JD', 272),
  ('N524MW', 272),
  ('N534PD', 267),
  ('N189JC', 285),
  ('N297E', 150),
  ('N35438', 285),
  ('N397E', 120),
  ('N497E', 120),
  ('N597E', 144),
  ('N911KC', 270),
  ('N912KC', 267),
  ('N913KC', 267),
  ('N737ZA', 474),
  ('N991YC', 120),
  ('N213PF', 267),
  ('N221LA', 267),
  ('N223LA', 267),
  ('N224LA', 267),
  ('N225LA', 267),
  ('N226LA', 267),
  ('N228LA', 240),
  ('N230LA', 267),
  ('N232LA', 267),
  ('N233LA', 267),
  ('N267LA', 267),
  ('N472LA', 267),
  ('N665PD', 240),
  ('N913WB', 240),
  ('N104RC', 150),
  ('N535JP', 150),
  ('N6330C', 315),
  ('N732WQ', 300),
  ('N950JE', 240),
  ('N950LA', 240),
  ('N951LA', 240),
  ('N951LB', 240),
  ('N952JH', 240),
  ('N953LA', 240),
  ('N954LA', 240),
  ('N955LA', 240),
  ('N956LA', 240),
  ('N957LA', 240),
  ('N958LA', 240),
  ('N959LA', 240),
  ('N960LA', 240),
  ('N961LA', 240),
  ('N961SD', 240),
  ('N962LA', 240),
  ('N963SD', 240),
  ('N966SD', 240),
  ('N166PD', 222),
  ('N462PD', 222),
  ('N641EG', 240),
  ('N226PD', 240),
  ('N28LB', 240),
  ('N29LB', 240),
  ('N9495F', 210),
  ('N9549F', 210),
  ('N165PW', 492),
  ('N214SB', 300),
  ('N265PW', 492),
  ('N305SB', 144),
  ('N307SB', 210),
  ('N308SB', 228),
  ('N309SB', 144),
  ('N625SB', 180),
  ('N631SB', 267),
  ('N803SB', 150),
  ('N831SB', 267),
  ('N832SB', 267),
  ('N833SB', 267),
  ('N834SB', 267),
  ('N835SB', 267),
  ('N836SB', 267),
  ('N313DP', 275),
  ('N319MW', 275),
  ('N670PC', 275),
  ('N709WG', 275),
  ('N989RL', 228),
  ('N881SD', 267),
  ('N882SD', 267),
  ('N883SD', 267),
  ('N884SD', 267),
  ('N181SD', 144),
  ('N183SD', 267),
  ('N185SD', 267),
  ('N186SD', 144),
  ('N6045C', 285),
  ('N960RN', 492),
  ('N893RC', 420),
  ('N205SD', 144),
  ('N205VC', 144),
  ('N206VC', 180),
  ('N32240', 144),
  ('N911VC', 180),
  ('N371DM', 450),
  ('N47PS', 400),
  ('N1576F', 150),
  ('N8372F', 150),
  ('N9298F', 210),
  ('N9686F', 210),
  ('N125AP', 267),
  ('N21475', 400),
  ('N6227', 267),
  ('N67662', 180),
  ('N917FW', 180),
  ('N911FW', 270),
  ('N206FW', 180),
  ('N505FW', 270),
  ('N111NK', 267),
  ('N820PM', 272),
  ('N312SD', 267),
  ('N731SD', 120),
  ('N915SD', 120),
  ('N71LC', 267),
  ('N72LC', 240),
  ('N73LC', 267),
  ('N74LC', 300),
  ('N407KB', 275),
  ('N407LM', 275),
  ('N407NL', 275),
  ('N481RC', 180),
  ('N552CH', 275),
  ('N866DM', 285),
  ('N103JP', 275),
  ('N311JP', 120),
  ('N312JP', 180),
  ('N313JP', 180),
  ('N314JP', 275),
  ('N317JP', 180),
  ('N92JP', 275),
  ('N109BC', 216),
  ('N257BC', 216),
  ('N265BC', 215),
  ('N268BC', 215),
  ('N781BC', 267),
  ('N782BC', 267),
  ('N783BC', 267),
  ('N101TN', 320),
  ('N227ND', 267),
  ('N245HC', 420),
  ('N413JM', 267),
  ('N717CD', 267),
  ('N911DG', 267),
  ('N1SD', 240),
  ('N2SD', 240),
  ('N43SD', 267),
  ('N14806', 267),
  ('N58501', 320),
  ('N518DS', 275),
  ('N618DS', 275),
  ('N718DS', 275),
  ('N401H', 275),
  ('N506MC', 275),
  ('N175SC', 267),
  ('N176SC', 267),
  ('N401MP', 300),
  ('N772GJ', 594),
  ('N551CP', 150),
  ('N552CP', 270),
  ('N553CP', 150),
  ('N556CP', 150),
  ('N557CP', 150),
  ('N559CP', 270),
  ('N951CP', 150),
  ('N952CP', 150),
  ('N720DP', 275)
) as durations(tail, nominal_endurance_min)
join public.aircraft
  on aircraft.tail = durations.tail
on conflict (aircraft_id) do update set
  nominal_endurance_min = excluded.nominal_endurance_min,
  reserve_min = excluded.reserve_min,
  source_note = excluded.source_note,
  updated_at = excluded.updated_at;
